### ISSUE TITLE
園児の一覧取得の Web API作成

### ISSUE THREAD

**Issue by k-imamura** [its-succ/rabbit-server#11]
一覧取得

```
GET http://localhost:3000/api/children/
```

**Comment by potatosh** [comment]
あれ、これって https://github.com/its-succ/rabbit-server/issues/8 に含まれていないんでしたっけ・・・タイトルには「登録・更新・削除」って書いてありますが、 CRUD の Web API 作成なのでこっちで進めちゃってました・・・

**Comment by potatosh** [comment]
#8 と一緒に進めることにしました。
