### ISSUE TITLE
プロジェクトの枠を作成する

### ISSUE THREAD

**Issue by fossamagna** [its-succ/rabbit-server#2]
現時点では`package.json`くらいしかないので、サーバが起動して最初のページが表示できる状態にする。[express-generator](http://expressjs.com/en/starter/generator.html)を使えばサクッと作れるはず。

**Comment by sakai-y** [comment]
・テンプレートエンジン
・スタイルシート
それぞれ、何を選択しましょうか。

**Comment by fossamagna** [comment]
個人的には jade より ejs が好みかな。スタイルシートは直CSSかな。
