### ISSUE TITLE
configを作成する

### ISSUE THREAD

**Issue by sakai-y** [its-succ/rabbit-server#25]
dbのパスとか、コードに直に書きたくない。

**Comment by fossamagna** [comment]
https://github.com/lorenwest/node-config とか。

**Comment by sakai-y** [comment]
:+1:

**Comment by sakai-y** [comment]
configファイルをcsonにするかyamlにするかで迷い中

**Comment by fossamagna** [comment]
どっちもコメントかけるしなー、個人的に馴染みがあるのはyamlだけど。csonの良さって何かな？
