### ISSUE TITLE
システム利用者のユーザモデルを検討する

### ISSUE THREAD

**Issue by minakamoto** [its-succ/rabbit-server#31]

**Comment by minakamoto** [comment]
システム利用者って、このシステムを管理する立場の人で良いですかね？
そして、何するんでしたっけ？？:sweat_smile:
- 園児の参照、登録、更新
- カード（保護者と園児の紐付け？）の参照、登録、更新
- システム利用者の管理も？

システム利用者に絶対必要そうなフィールドは、
- ユーザID
- パスワード

で、必要かも、
- メール（メールがユーザID ?）
- 名前
- 担当クラス
- ログイン可否フラグ
- 権限区分（なんでもできる人、一部の機能だけ）

ですかね？？？

**Comment by fossamagna** [comment]
できること(できないといけないこと)は上記に通りだと思います。
で、利用者のプロパティはまずは、ユーザIDとパスワードで始めたらいいかと思います。

**Comment by minakamoto** [comment]
了解です 👍

**Comment by fossamagna** [comment]
@minakamoto これ close で 🆗  ?

**Comment by minakamoto** [comment]
👌 

closeします
