### ISSUE TITLE
登退園のAPIを検討する

### ISSUE THREAD

**Issue by sakai-y** [its-succ/rabbit-server#36]
- モデル
- REST

**Comment by sakai-y** [comment]
カード通したら、サーバー側で登園か退園かの判断をDBから判断するんでしたっけ？
それともクライアント側から登園か退園か指定するんでしたっけ？

**Comment by fossamagna** [comment]
後者(クライアントが指定)を想定していました。

**Comment by sakai-y** [comment]
登退園の記録って全件取得すると巨大なレスポンスになっちゃいますよね。月または日を指定させるのがいいか

**Comment by fossamagna** [comment]
APIとしては`年月`または`年月日`指定で取得できれば 🆗 かと思います。期間指定できればいいのかな。

**Comment by sakai-y** [comment]
ひとまず登園・退園と情報取得を書いてみました。

https://github.com/its-succ/rabbit-server/wiki/Web-API%EF%BC%88%E7%99%BB%E9%80%80%E5%9C%92%EF%BC%89

あと、更新と削除を追加予定です。

**Comment by sakai-y** [comment]
更新と削除も追加しました。

**Comment by fossamagna** [comment]
`POST /api/records/leave`はどの登園に対する退園になるんでしたっけ？

**Comment by sakai-y** [comment]
日時が最も新しいもの・・・かな

**Comment by fossamagna** [comment]
対象日時はリクエストする側に指定させたほうがいいかもしれないですね。登園も退園も。

**Comment by sakai-y** [comment]
`time`必須にする？

**Comment by fossamagna** [comment]
レスポンスでいう`date`ですかね。

**Comment by fossamagna** [comment]
うーん、実際には日時が最も新しいものでも実際に困ることはないのかも。。。。

でも、次のパターンだとまずいな。
1. 6/23 に登園処理実施
2. 6/23 に退園処理忘れ
3. 6/24 に登園処理忘れ
4. 6/24 に退園処理実施

**Comment by sakai-y** [comment]
`time`に`date`入ってるけど・・・日が変わるケース？

**Comment by sakai-y** [comment]
確かに

**Comment by fossamagna** [comment]
現実としては、日付がわかるまで保育園やってないとは思いますが。

**Comment by fossamagna** [comment]
対象日がいつなのかは重要な気がするので指定したほうがいいかも。日付指定なら、退園処理時に「その日は登園してないよ」とか言えるし。言うかどうかは置いといて。登園時間なしで退園時間だけのレコードもあってはいいと思う。

**Comment by sakai-y** [comment]
この前、テレビで深夜まで預かってる保育園やってた

**Comment by fossamagna** [comment]
そんなんあるのかー、知らんかった。ならなおさら日付はいるかも。

**Comment by sakai-y** [comment]
日付入れました。

**Comment by minakamoto** [comment]
[登退園情報取得](https://github.com/its-succ/rabbit-server/wiki/Web-API%EF%BC%88%E7%99%BB%E9%80%80%E5%9C%92%EF%BC%89#%E7%99%BB%E9%80%80%E5%9C%92%E6%83%85%E5%A0%B1%E5%8F%96%E5%BE%97)の
`GET /api/records/{id}{?month,date,child}`
って、
`{id}`もしくは、`{month,date,child}`の中のいずれかを指定する感じですか？
`{month,date,child}`の場合は全部？

**Comment by sakai-y** [comment]
こうかな `({id} | {child}?({month} | {date}))`
同時に指定された場合は、`{id}` > `{child}` = (`{date}` > `{month}`)

**Comment by minakamoto** [comment]
🙆

**Comment by sakai-y** [comment]
[登退園情報取得](https://github.com/its-succ/rabbit-server/wiki/Web-API%EF%BC%88%E7%99%BB%E9%80%80%E5%9C%92%EF%BC%89#%E7%99%BB%E9%80%80%E5%9C%92%E6%83%85%E5%A0%B1%E5%8F%96%E5%BE%97)の記述を少し変更しました。

**Comment by fossamagna** [comment]
🆗

**Comment by minakamoto** [comment]
🙆

**Comment by k-imamura** [comment]
LGTM

**Comment by sakai-y** [comment]
だん
