### ISSUE TITLE
各モデルのCRUD APIを作る

### ISSUE THREAD

**Issue by potatosh** [its-succ/rabbit-server#4]
Child以外のモデル(Card, Check, CheckHistory)についてもCRUD APIを作成する。

**Comment by fossamagna** [comment]
この issue 内容が大きいのと、レイヤーで閉じた感じなので一旦closeにしていいですか？ #8 みたいな感じでいきたいです。

**Comment by potatosh** [comment]
構いませんが、 #8 を細分化したチケットとして考えるのはあんまり良くないんでしょうかね？（まあそうするなら最初から細分化したもの全部挙げとくべきなんですけど）

**Comment by fossamagna** [comment]
#8 ではCard, Check, CheckHistoryはまだ出てこないので、このissueが扱うのがChildのみならこのissueでもOKかと思います。

**Comment by potatosh** [comment]
あー、それは確かにそうですね。わかりました。
