### ISSUE TITLE
園児の一覧を表示できる

### ISSUE THREAD

**Issue by fossamagna** [its-succ/rabbit-server#5]
園児の以下の内容を一覧表示できる
- ID
- 名前
- 性別

以下の作業が必要と思われる
- Mongodbへのサンプルデータの投入(seeder?)
- 一覧画面作成

**Comment by fossamagna** [comment]
@k-imamura このissueでやる内容が結構多いかもしれないので分割したほうがいいですかね？どうでしょう？

**Comment by k-imamura** [comment]
@fossamagna そうですね。園児一覧取得Web API作成、一覧画面作成は分けた方がいいです。あとは？？

**Comment by fossamagna** [comment]
@k-imamura では、画面とサーバで分けましょう。issue分けてもらっていいですか？

**Comment by k-imamura** [comment]
@fossamagna りょうかいしました！

**Comment by k-imamura** [comment]
園児一覧取得Web API作成はissue #11 に切り出しました。issueの説明からも削除しました。このissueでは画面の作成とサーバーとの連携部分を行います。

**Comment by k-imamura** [comment]
まだ実装は入れていないので目処立たず。本日勉強会終了時点で目処立てます。

**Comment by fossamagna** [comment]
@k-imamura どんな感じですか？

**Comment by k-imamura** [comment]
園児一覧だすのにnode bundle.js実行したら（間違ってます？）m.route(document.getElementById('root'), '/', {のところでdocumentがreference error だと言われてるところです。園児一覧作ったからとかではなく、最初のページすら出せてないです。

**Comment by k-imamura** [comment]
あ、ちなみに園児一覧はまだ全然中身はできていません

**Comment by fossamagna** [comment]
@k-imamura `npm start`でサーバが起動します。起動したらhttp://localhost:3000にアクセスしてください。bundle.jsはクライアントサイドのjsなのでnodeコマンドでは実行しないです。

**Comment by k-imamura** [comment]
@fossamagna 画面でました！わたし全然わかってないんですね～。サーバー作ってるのにそれすらどこかに忘れてました・・

**Comment by fossamagna** [comment]
一覧は表示できるようになったのでclose
