### ISSUE TITLE
MongoDBからRDBに変更する

### ISSUE THREAD

**Issue by fossamagna** [its-succ/rabbit-server#73]
- RDBはPostgreSQL(一旦は)
- ORMとして [Sequelize](http://docs.sequelizejs.com/en/v3/) を入れる

**Comment by fossamagna** [comment]
http://bookshelfjs.org/ もよさそう

**Comment by sakai-y** [comment]
Sequelizeがダントツっすね
https://npmcompare.com/compare/bookshelf,objection,orm,sequelize,sql-bricks

**Comment by fossamagna** [comment]
|                  | sequelize  | bookshelf  |
|-------------|-------------|-------------|
|スキーマ定義   | http://docs.sequelizejs.com/en/v3/docs/migrations/ | http://knexjs.org/#Migrations |
|モデル        | http://docs.sequelizejs.com/en/v3/api/model/ | http://bookshelfjs.org/#Model |
|関連           | http://docs.sequelizejs.com/en/v3/docs/associations/ | http://bookshelfjs.org/#associations |
|クエリ        | http://docs.sequelizejs.com/en/v3/docs/querying/ | http://bookshelfjs.org/#Model-instance-fetch |

どちらも一通りのことはできますね。
