### ISSUE TITLE
園児を登録・更新・削除できる

### ISSUE THREAD

**Issue by fossamagna** [its-succ/rabbit-server#8]
- Wikiに記載された園児のCRUDの Web API作成

**Comment by sakai-y** [comment]
このissueが含む範囲が不明確な気がします。
#5 と同じく一通り？

**Comment by fossamagna** [comment]
issueの説明に作業内容を書きました。

**Comment by potatosh** [comment]
園児にカードを紐付けることになってますが、園児に対応するカードが見つからない場合はどういう扱いにしたらいいでしょうかね・・・。404？それとも不整合とみなして別のエラーですかね？

**Comment by fossamagna** [comment]
@potatosh カードなしの園児も正常パターンだと思う。

**Comment by potatosh** [comment]
@fossamagna あー、カード無しならcardsの配列が空になるだけだからいいのか・・・確かに正常で良さそうですね。

**Comment by potatosh** [comment]
実装部分はいったんできました。あとはテストなんですが、 https://github.com/its-succ/rabbit-server/issues/18 と同じく mocha と supertest を試してみようと思います。
