### ISSUE TITLE
園児・カードのAPI体系を決定する

### ISSUE THREAD

**Issue by sakai-y** [its-succ/rabbit-server#9]

**Comment by potatosh** [comment]
``` javascript
{
  "cardId": "asdffdsa01234567",
  "owner": "鈴木信長",
  "child": "563c18760aadbd54221b46d9"
}
```

カードについては、 @fossamagna がIdobataに書いていたモデル体系だとこんな感じですかね？
https://idobata.io/ja/archives/organization/esm/room/its-cloudmobile/2015-12-04#message_13245897

**Comment by fossamagna** [comment]
こんな感じかね。

### 単一のカード情報の取得

```
GET /api/card/:cardId
```

レスポンスボディ

``` json
{
  "cardId": "asdffdsa01234567",
  "owner": "鈴木信長",
  "child": "563c18760aadbd54221b46d9"
}
```

### 全てのカード情報の取得

ページングのためのパラメータが必要かも。

```
GET /api/card
```

レスポンスボディ

``` json
[{
  "cardId": "asdffdsa01234567",
  "owner": "鈴木信長",
  "child": "563c18760aadbd54221b46d9"
}]
```

### カードの登録

```
POST /api/card
```

リクエストボディ

``` json
{
  "owner": "鈴木信長",
  "child": "563c18760aadbd54221b46d9"
}
```

### カードの更新

```
PUT /api/card/:cardId
```

リクエストボディ

``` json
{
  "owner": "鈴木信長",
  "child": "563c18760aadbd54221b46d9"
}
```

### カードの削除

```
DELETE /api/card/:cardId
```

**Comment by potatosh** [comment]
`cardId`はNFCタグのIDと理解していたんですが、登録や更新の時は必要ないのでしょうか。

**Comment by sakai-y** [comment]
こういう感じですね。
カードに対して園児は複数なので、こう？

``` json
  "children": ["563c18760aadbd54221b46d9"]
```

**Comment by fossamagna** [comment]
@sakai-y 確かに。

**Comment by sakai-y** [comment]
そうか。なんとなくドキュメントのidとカードIDは別で考えてたんですが、カードIDはユニークじゃないと困るので、イコールでいいですね。

**Comment by fossamagna** [comment]
そっすね。Mongdb上ではCardの`_id`はObjectIdを使わず、自分で採番する(カードのIDを使う)ようにすればいいのかなと。なのでJSON上も`cardId`ではなく`_id`かな。

**Comment by sakai-y** [comment]
こういうAPI仕様って、どう記述するとスッキリまとまるんですかね。
某PJではastahのマインドマップ使ってたけど、あれはちょっと。。。

[iodocs](http://www.mashery.com/api/io-docs)とか？

**Comment by fossamagna** [comment]
ここまでの話をまとめると、以下の仕様かなと思います。どうでしょう？

### 単一のカード情報の取得

```
GET /api/card/:id
```

レスポンスボディ

``` json
{
  "_id": "asdffdsa01234567",
  "owner": "鈴木信長",
  "children": ["563c18760aadbd54221b46d9"]
}
```

### 全てのカード情報の取得

ページングのためのパラメータが必要かも。

```
GET /api/card
```

レスポンスボディ

``` json
[{
  "_id": "asdffdsa01234567",
  "owner": "鈴木信長",
  "children": ["563c18760aadbd54221b46d9"]
}]
```

### カードの登録

```
POST /api/card
```

リクエストボディ

``` json
{
  "_id": "asdffdsa01234567",
  "owner": "鈴木信長",
  "children": ["563c18760aadbd54221b46d9"]
}
```

### カードの更新

```
PUT /api/card/:id
```

リクエストボディ

``` json
{
  "owner": "鈴木信長",
  "children": ["563c18760aadbd54221b46d9"]
}
```

### カードの削除

```
DELETE /api/card/:id
```

**Comment by sakai-y** [comment]
:+1:

**Comment by sakai-y** [comment]
園児をキーにカード探したいケースってないかな

**Comment by fossamagna** [comment]
@sakai-y あるとは思うけど、`/api/children/`配下のAPIでもいいのかなと。

**Comment by sakai-y** [comment]
`GET /api/children/:id/card`みたいな？

**Comment by fossamagna** [comment]
`GET /api/children/:id`のレスポンスのJSONのプロパティに含めてもいいかなと。

**Comment by sakai-y** [comment]
なるほど

**Comment by sakai-y** [comment]
そういえば、`/api/card`って、`/api/cards`にすべき？

**Comment by fossamagna** [comment]
そうっすね。複数形かな。今議論しているAPIは固まったらWikiにまとめて、このissueはcloseしましょう。その時に一括で複数形に統一しますか。

**Comment by sakai-y** [comment]
:ok:

**Comment by fossamagna** [comment]
この仕様でよければ、Wikiにまとめてcloseしますね。

**Comment by potatosh** [comment]
:ok:

**Comment by minakamoto** [comment]
LGTM

**Comment by fossamagna** [comment]
wikiに記載したのでcloseします。

**Comment by potatosh** [comment]
すみません、closeした後ですが https://github.com/its-succ/rabbit-server/issues/9#issuecomment-169867498 に従って `GET /api/children/:id` のレスポンスに `cards` を含めてみました。

```
GET http://localhost:3000/api/children/{id}

{
  "name" : "鈴木一郎",
  "birthday" : "2013-04-01",
  "sex" : "M",
  "cards" : [{
    "_id" : "asdffdsa01234567",
    "owner" : "鈴木信長",
    "children" : ["563c18760aadbd54221b46d9"]
  }, {
    "_id" : "zxcvvcxz87654321",
    "owner" : "鈴木芳恵",
    "children" : ["563c18760aadbd54221b46d9"]
  }]
}
```

こんな感じでしょうか。

**Comment by fossamagna** [comment]
@potatosh :+1: Wikiにも反映しといてもらえると助かります。

**Comment by sakai-y** [comment]
手持ち無沙汰なのでWiki更新しておきます

**Comment by potatosh** [comment]
@sakai-y :pray:

**Comment by sakai-y** [comment]
更新しました

**Comment by potatosh** [comment]
:+1:
